version: '3.8'

services:
  fastapi:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.9
    volumes:
      - ./:/app
    ports:
      - "8000:80"
    environment:
      - MODULE_NAME=main  # The name of your FastAPI app (without .py)
      - VARIABLE_NAME=app  # The name of the FastAPI app variable
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
